### PR TITLE
Remove unnecessary rule suffix

### PR DESCRIPTION
**Pull request by bpesch**
Hi!
First of all, great project!

While setting up the configuration in a private project, I noticed the "Rule" suffix on all bundled rules.
I don't think this is necessary since all of the classes live in the `\Danger\Rule` namespace already.

### CODE REVIEW

**Comment by shyim** [comment]
You are right 🙈 
Can you make the old one still working? 

Like 
```
/** @deprecated use DisallowRepeatedCommits instead **/
class DisallowRepeatedCommitsRule extends DisallowRepeatedCommits

**Comment by bpesch** [comment]
> Can you make the old one still working?

I updated the code to make the old ones still working.
Maybe [trigger_deprecation](https://github.com/symfony/deprecation-contracts/blob/main/function.php#L23) should be used here?

**Comment by shyim** [comment]
Good idea. 👍

**Comment by bpesch** [comment]
Added! While adding the constants to the `Application` class, I noticed a type warning.


I fixed that in a separate commit in case you don't want to merge it.

**Comment by shyim** [comment]
Can you run the cs-fixer? Seems aborted

**Comment by bpesch** [comment]
`@codeCoverageIgnore` the deprecated classes?

**Comment by shyim** [comment]
Yup would be good 👍

**Comment by bpesch** [comment]
Also just noticed that you might want to remove the "incomplete" label again if all checks passed.
https://github.com/shyim/danger-php/blob/main/.danger.php#L31

**Comment by shyim** [comment]
Thanks!

Feel free to create an PR :)

**Pull request merged**
